### ISSUE TITLE
Adding new frameworks?

### ISSUE THREAD

**Issue by will-lumley** [seyfeddin/awesome-macos#1]
Hi there,
I have developed a couple native macOS open source frameworks/libraries that I think would be a great fit for listing on this repo. How would I go about suggesting these?

**Comment by seyfeddin** [comment]
@will-lumley absolutely, just send a PR and I'll merge them

**Comment by will-lumley** [comment]
@seyfeddin I've added the PR - let me know if you have any issues :)

**Comment by seyfeddin** [comment]
Merged. Thanks!
